### ISSUE TITLE
Pullable inner sources are flattened to a listeable output source

### ISSUE THREAD

**Issue by mperktold** [avinashcodes/callbag-flat-map#4]
I would expect that pullable inner sources are combined to a pullable outer source, but that is not the case.

Consider the following example:
```javascript
const output = pipe(
    of("a", "b", "c"),
    flatMap(x => range(0, 2), (a, b) => a  + b),
    toIterable
);

for (x of output) {
    console.log(x);
}
```
You would expect it to log `a0`, `a1`, `a2`, `b0`, etc., but it doesn't log anything.

This is because `toIterable` expects its input source to be pullable, and on every call to `next()` on its iterator, it pulls the next value, and returns it if present.

But since `flatMap` passes a listenable source to `toIterable`, the sink is already terminated before the first call to `next()`.

Will create a pull request soon.

**Comment by avinashcodes** [comment]
@mperktold I got your point now.  `toIterable` works only with pull-based sources. It's mentioned in the description of that module.
> Convert a synchronous pullable callbag source to an Iterable.

 We would have have similar issues for example below
```js
        const output = pipe(
	    interval(500),
	    toIterable
	);
        for (x of output) {
           console.log(x);
        }
```
So I guess it's expected to use such operators in right context.

**Comment by mperktold** [comment]
> So I guess it's expected to use such operators in right context.

Right, but there is a difference between `interval`and `flatMap` here.

`interval` is a source factory, so it must choose by itself whether to create a pullable or listenable source. The fact that this choice is made in favor of listenable sources is quite intuitive, since this is really a push-based process. And, more importantly, this choice is documented in the readme.

`flatMap`, on the other hand, flattens the inner sources. Therefore, the most intuitive behavior would be to create an output source of the same type, i.e. flatten pullable inner sources to a pullable output source, and listenable inner sources to a listenable output source.

That‘s what I did in my pull request. I admit that the resulting code has become more complex than the original one, so leaving it as is is certainly an option.

But in any case, the readme should clearly document what kinds of sources are produced in which cases.

**Comment by avinashcodes** [comment]
@mperktold You're right. I could've given a better example to make it more clear. 
The below code uses flatten and doesn't log anything either and exits. 
```js
        const output = pipe(
	    interval(500),
	    map(x =>pipe(
	    	fromIter([10, 20]),
	    	map(num => x  + ' ' + 10)
    	    )),
	    flatten,
	    toIterable
	);
        for (x of output) {
	    console.log(x);
	}
```


I've pulled your code (both from this PR and callbag-flat-map-lazy package) and ran the below code
```js
        const output = pipe(
	    interval(500),
	    flatmapLazy(x => fromIter([0,1, 2]), (a, b) => a  + b),
	    toIterable
	);
```
It doesn't log anything and blocked. Most likely stuck in the `while(true)` loop.

So what I was trying to mention in the previous comment is
1. Operators work with either pullable sources/listenable sources. 
2. toIterable is a helper to cast a pullable source into iterable. It will be useful while posting back the results to outside world which doesn't know about `callbags`
3. An `iterable` source means there should be a data available whenever we try to pull. In this case, we don't have such root source. so it's not possible to pull the data. In other words, we can't force a true async operation to be iterable. We need an `async iterable` for that or cache the results and send it when async operation completed.

So my point is `toIterable` needs to be used only when it is bound to a pullable source. Otherwise, logically it wouldn't/shouldn't do anything and that is expected by definition.

**Comment by mperktold** [comment]
> So my point is `toIterable` needs to be used only when it is bound to a pullable source. Otherwise, logically it wouldn't/shouldn't do anything and that is expected by definition.

I agree, there is good reason `toIterable` works in this way. And there are others, like `toAsyncIterable`, which pose similar requirements on the input source. Some things can only be done if the input source is pullable, and that‘s OK.

However, I don‘t see such conceptual limitations in the case of`flatMap`. On the contrary, because of such limitations of other operators, it should try to keep pullable sources pullable.

In your example with `flatten`, the problem is `interval`, which is async and thus not compatible with `toIterable`. A programmer could make such a mistake, but it wouldn‘t be hard to spot.

Consider this example:

```javascript
        const output = pipe(
	    range(0, 3),
	    map(x => pipe(
	    	fromIter([10, 20]),
	    	map(num => x  + ' ' + 10)
    	    )),
	    flatten,
	    toIterable
	);
        for (x of output) {
	    console.log(x);
	}
```

Here everything is synchronous and should work fine.

Now suppose we do some refactoring and replace `map` and `flatten` with `flatMap`:

```javascript
        const output = pipe(
	    range(0, 3),
	    flatMap(
                x => fromIter([10, 20]),
	        num => x  + ' ' + 10
    	    ),
	    toIterable
	);
        for (x of output) {
	    console.log(x);
	}
```

Things will suddenly stop working, although the semantics of the code is almost the same. There is nothing in the name nor in the description of the `flatMap` module suggesting that you cannot use it the way we used `flatten` in the previous example.

So unlike with `interval`, the bug is quite hard to spot. The incompatibility between `flatMap` and `toIterable` is not forced on a conceptual level. It’s just an implementation decision.

**Comment by avinashcodes** [comment]
Hi @mperktold ,   I was under the impression that you're trying to use a root listenable source and inner pullable sources with toIterable sink. 
Hence my previous two comments and closing the issue. I am really sorry for that.
As you said, there's clearly a bug with the operator with pullable sources. Fixed it in the [commit](https://github.com/avinashcodes/callbag-flat-map/commit/bf1b66e59da724917b981634517e558e62f81594) and published patch version. 

I really appreciate your effort to raise the issue and thorough explanation :) 👍
